APP_CAPTION: "Collect cheese if you can"

SCREEN_WIDTH: 1920
SCREEN_HEIGHT: 1080
SCALE_RATE: 1.0

FULLSCREEN_MODE: False

GAME_DELAY: 500
GAME_STATE_COMMENT_PRINTED_DELAY: 500
WINNER_PRINTED_DELAY: 4000
NO_WINNER_PRINTED_DELAY: 2000

MAX_ACTIONS_NUMBER: 216
MAX_DO_NOTHING_ACTIONS_NUMBER: 3

MAX_ACTIONS_NUMBER_ACHIEVED_GAME_RESULT: "CAT_WON"

HONEST_MODE: False

WORLD_WIDTH: 9
WORLD_HEIGHT: 9

WALLS_NUMBER: 9
CHEESE_NUMBER: 5

HOLES_NUMBER: 2
